firewall_v4_default_rules: {}

routes_commands: "{{ routes_merged.values() | list }}"
routes_default:
  000 route de controle: ip route replace 10.8.0.0/24 via 172.16.5.1 dev {{ interfaces.controle.name }} onlink
routes_group: {}
routes_host: {}
routes_merged: "{{ routes_default | combine(routes_group) | combine(routes_host) }}"
