
ansible_user: root
ansible_host: ens18.address

interfaces_ether_interfaces:
#ceci est un exemple
  - device: ens18
    bootproto: static
    address: "{{ ens18.address }}"
    netmask: 255.255.255.0
    gateway: "{{ ens18.gateway }}"
    dnsnameservers: 192.168.130.202 212.27.40.240 212.27.40.241
    dnssearch: b120.esisar.fr

  - device: ens19
    bootproto: static
    address: "{{ ens19.address }}"
    netmask: 255.255.255.0
    gateway: "{{ ens19.gateway }}"

firewall_v4_group_rules: {}