---

- hosts: all
  roles:
    - { role: ansible-role-ip-route, tags: routes }
    - { role: ansible-rsyslog, tags: rsyslog}

- hosts: vpn
  roles:
    - { role: Stouts.openvpn, tags: openvpn }

- hosts: vpn_intranet
  roles:
    #- { role: Stouts.openvpn, tags: openvpn }

- hosts: ldap
  roles:
    #- { role: ansible-openldap, tags: ldap }

- hosts: dns_publique
  roles:
    - { role: ansible-role-bind, tags: bind }

- hosts: web_failover
  roles:
    - { role: ansible-keepalived, tags: keepalived }
    - { role: ansible-role-nginx, tags: nginx }

- hosts: dmz_web
  roles:
    - { role: ansible-role-nginx, tags: nginx }

- hosts: load_bal
  tasks:
    - name: activate ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      tags: forwarding
  roles:
    - { role: ansible-keepalived, tags: keepalived }
    - { role: ansible-role-haproxy, tags: haproxy }

- hosts: fw
  tasks:
    - name: activate ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      tags: forwarding
    - name: Install vlan (debian/ubuntu)
      apt: name=vlan state=latest
      tags: vlan
    - name: set hostname
      copy: content="{{ inventory_hostname }}" dest=/etc/hostname
      tags: hostname
  roles:
    - { role: ansible-resolv, tags: resolv }
    - { role: ansible-role-interfaces, tags: interface }
    - { role: ansible-role-firewall, tags: iptables }
    - { role: ansible-keepalived, tags: keepalived }
    - { role: ansible-conntrackd, tags: conntrackd }