ansible_user: root

interfaces:
  controle:
    name: eth0

firewall_v4_group_rules:
  001 default input policy:
    - -P INPUT ACCEPT
  002 default output policy:
    - -P OUTPUT ACCEPT
  003 default forward policy:
    - -P FORWARD ACCEPT
