---

- hosts: fw
  roles:
    - role: MichaelRigart.interfaces
      tags: [ 'interface' ]
    - role: mikegleasonjr.firewall
      tags: [ 'firewall' ]
    - role: tcomerma.keepalived
      tags: [ 'keepalived' ]