
- hosts: vm
  tasks:
    - name: remove script
      file: 
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/iptables/rules.v4
        - /etc/iptables/rules.v6