public_address: 192.168.130.54
interface:
  dmz_publique:
    address: 192.168.30.2

bind_listen_ipv4: true
bind_role: master
bind_forwarder: 192.168.130.202
bind_view_interne: 192.168.0.0/17
bind_view_externe: any

bind_zones_interne:
  esihosting.com:
    ns_primary: ns1.esihosting.com
    mail: abuse.esihosting.com
    serial: 2017110406
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: 192.168.30.2 }
      - { name: '@', type: mx, priority: 10, value: mail }
      - { name: mail, type: a, value: 192.168.30.3 }
  rascasse.fr:
    ns_primary: ns1.rascasse.fr
    mail: abuse.esihosting.com
    serial: 2017110501
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: 192.168.30.2 }
      - { name: '@', type: a, value: 1.2.3.4 }
  evilcorp.hell:
    ns_primary: ns1.evilcorp.hell
    mail: abuse.esihosting.com
    serial: 2017110501
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: 192.168.30.2 }
      - { name: '@', type: a, value: 5.6.7.8 }

bind_zones_externe:
  esihosting.com:
    ns_primary: ns1.esihosting.com
    mail: abuse.esihosting.com
    serial: 2017110406
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: '{{ public_address }}' }
      - { name: '@', type: mx, priority: 10, value: mail }
      - { name: mail, type: a, value: 192.168.130.55 }
  rascasse.fr:
    ns_primary: ns1.rascasse.fr
    mail: abuse.esihosting.com
    serial: 2017110501
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: '{{ public_address }}' }
      - { name: '@', type: a, value: 1.2.3.4 }
  evilcorp.hell:
    ns_primary: ns1.evilcorp.hell
    mail: abuse.esihosting.com
    serial: 2017110501
    dnssec: yes
    entries:
      - { name: '@', type: ns, value: ns1 }
      - { name: ns1, type: a, value: '{{ public_address }}' }
      - { name: '@', type: a, value: 5.6.7.8 }