
interfaces:
  controle:
    name: ens18
    address: 172.16.5.3
  extern:
    name: ens19
    address: 192.168.130.57
    gateway: 192.168.130.254
  fw_link:
    name: ens20.120
    address: 192.168.20.2
  dmz_vpn_ext:
    name: ens20.110
    address: 192.168.10.252
  dmz_vpn_int:
    name: ens20.100
    address: 192.168.0.252
  dmz_publique:
    name: ens20.130
    address: 192.168.30.252
  dmz_privee:
    name: ens20.140
    address: 192.168.40.252
  dmz_client_intranet_externe:
    name: ens20.150
    address: 192.168.50.252
  dmz_client_http:
    name: ens20.160
    address: 192.168.60.252
  sw_802_1:
    name: ens20.170
    address: 192.168.70.252


firewall_v4_host_rules: {}

keepalive_prio: 50
keepalive_peer: 192.168.20.1