
# Default settings (See OpenVPN documentation)
openvpn_host: 192.168.130.53              # The server address
openvpn_port: 7001
openvpn_proto: tcp
openvpn_server: 10.9.0.0 255.255.255.0              # Set empty for skip
openvpn_cipher: AES-256-CBC                              # Encryption algorithm
openvpn_tls_auth : true                            # Enable perfect forward secracyxy
openvpn_client_to_client: no
openvpn_key_country: FR
openvpn_key_province: FR
openvpn_key_city: FR
openvpn_key_org: Esihost
openvpn_key_email: esihost@myhost.mydomain
openvpn_key_size: 2048
openvpn_server_options:
  - push "route 192.168.0.0 255.255.128.0"

openvpn_lxc_tun_correction: true

openvpn_clients: [rascasse]                         # Make clients certificate

# Use PAM authentication
openvpn_use_pam: no

# Use simple authentication (default is disabled)
openvpn_simple_auth: yes

# Whether to embed CA, cert, and key info inside client OVPN config file.
openvpn_unified_client_profiles: yes


routes_host:
  100 routage des clients vpn: ip route replace 192.168.0.0/17 via 192.168.0.254 dev eth2 onlink
